// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolMedical_DataAccess.Entities;

#nullable disable

namespace SchoolMedical_DataAccess.Migrations
{
    [DbContext(typeof(SchoolhealthdbContext))]
    [Migration("20260714090410_UpdateDBWithNewEntities")]
    partial class UpdateDBWithNewEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SchoolMedical_DataAccess.Entities.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("ParentId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "Email")
                        .IsUnique();

                    b.HasIndex(new[] { "ParentId" }, "FK_Account_Parent");

                    b.HasIndex(new[] { "Role" }, "IDX_Account_Role");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("SchoolMedical_DataAccess.Entities.Healthcheckupevent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("DateOccurred")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateSignupEnd")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateSignupStart")
                        .HasColumnType("datetime");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CreatedBy" }, "IDX_HealthCheckupEvent_CreatedBy");

                    b.ToTable("healthcheckupevents", (string)null);
                });

            modelBuilder.Entity("SchoolMedical_DataAccess.Entities.HealthcheckupeventStudent", b =>
                {
                    b.Property<string>("HealthcheckupeventId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StudentId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ResultSummary")
                        .HasColumnType("text");

                    b.Property<DateTime>("SignupDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("HealthcheckupeventId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("healthcheckupevent_student", (string)null);
                });

            modelBuilder.Entity("SchoolMedical_DataAccess.Entities.Incidentrecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("DateOccurred")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("HandleBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IncidentType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "HandleBy" }, "IDX_IncidentRecord_HandleBy");

                    b.HasIndex(new[] { "StudentId" }, "IDX_IncidentRecord_StudentId");

                    b.ToTable("incidentrecords", (string)null);
                });

            modelBuilder.Entity("SchoolMedical_DataAccess.Entities.Medicalsupply", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool?>("IsAvailable")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValueSql("'1'");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CreatedBy" }, "IDX_MedicalSupply_CreatedBy");

                    b.ToTable("medicalsupplies", (string)null);
                });

            modelBuilder.Entity("SchoolMedical_DataAccess.Entities.Medicine", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool?>("IsAvailable")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValueSql("'1'");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CreatedBy" }, "IDX_Medicine_CreatedBy");

                    b.ToTable("medicines", (string)null);
                });

            modelBuilder.Entity("SchoolMedical_DataAccess.Entities.Medicinerequest", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("DateSent")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ForStudent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RequestBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ForStudent" }, "IDX_MedicineRequest_ForStudent");

                    b.HasIndex(new[] { "RequestBy" }, "IDX_MedicineRequest_RequestBy");

                    b.ToTable("medicinerequests", (string)null);
                });

            modelBuilder.Entity("SchoolMedical_DataAccess.Entities.Meeting", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("HandleBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("ParentAttended")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "HandleBy" }, "IDX_Meeting_HandleBy");

                    b.HasIndex(new[] { "StudentId" }, "IDX_Meeting_StudentId");

                    b.ToTable("meeting", (string)null);
                });

            modelBuilder.Entity("SchoolMedical_DataAccess.Entities.Studenthealthrecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Allergies")
                        .HasColumnType("text");

                    b.Property<string>("ChronicDiseases")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Hearing")
                        .HasColumnType("text");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Vision")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CreatedBy" }, "IDX_StudentHealthRecord_CreatedBy");

                    b.HasIndex(new[] { "StudentId" }, "IDX_StudentHealthRecord_StudentId")
                        .IsUnique();

                    b.ToTable("studenthealthrecords", (string)null);
                });

            modelBuilder.Entity("SchoolMedical_DataAccess.Entities.Treatmentrecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("StudentHealthRecordId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Treatment")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "StudentHealthRecordId" }, "IDX_TreatmentRecord_StudentHealthRecordId");

                    b.ToTable("treatmentrecords", (string)null);
                });

            modelBuilder.Entity("SchoolMedical_DataAccess.Entities.Vaccineevent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("DateOccurred")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateSignupEnd")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateSignupStart")
                        .HasColumnType("datetime");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CreatedBy" }, "IDX_VaccineEvent_CreatedBy");

                    b.ToTable("vaccineevents", (string)null);
                });

            modelBuilder.Entity("SchoolMedical_DataAccess.Entities.VaccineeventStudent", b =>
                {
                    b.Property<string>("VaccineeventId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StudentId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ResultSummary")
                        .HasColumnType("text");

                    b.Property<DateTime>("SignupDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("VaccineeventId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("vaccineevent_student", (string)null);
                });

            modelBuilder.Entity("SchoolMedical_DataAccess.Entities.Vaccinerecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("StudentHealthRecordId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Vaccine")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "StudentHealthRecordId" }, "IDX_VaccineRecord_StudentHealthRecordId");

                    b.ToTable("vaccinerecords", (string)null);
                });

            modelBuilder.Entity("SchoolMedical_DataAccess.Entities.Account", b =>
                {
                    b.HasOne("SchoolMedical_DataAccess.Entities.Account", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Account_Parent");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SchoolMedical_DataAccess.Entities.Healthcheckupevent", b =>
                {
                    b.HasOne("SchoolMedical_DataAccess.Entities.Account", "CreatedByNavigation")
                        .WithMany("HealthcheckupeventCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_HealthCheckupEvent_CreatedBy");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("SchoolMedical_DataAccess.Entities.HealthcheckupeventStudent", b =>
                {
                    b.HasOne("SchoolMedical_DataAccess.Entities.Healthcheckupevent", "Healthcheckupevent")
                        .WithMany("HealthcheckupeventStudents")
                        .HasForeignKey("HealthcheckupeventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HealthcheckupeventStudent_Event");

                    b.HasOne("SchoolMedical_DataAccess.Entities.Account", "Student")
                        .WithMany("HealthcheckupeventStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HealthcheckupeventStudent_Student");

                    b.Navigation("Healthcheckupevent");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolMedical_DataAccess.Entities.Incidentrecord", b =>
                {
                    b.HasOne("SchoolMedical_DataAccess.Entities.Account", "HandleByNavigation")
                        .WithMany("IncidentrecordHandleByNavigations")
                        .HasForeignKey("HandleBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_IncidentRecord_HandleBy");

                    b.HasOne("SchoolMedical_DataAccess.Entities.Account", "Student")
                        .WithMany("IncidentrecordStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_IncidentRecord_Student");

                    b.Navigation("HandleByNavigation");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolMedical_DataAccess.Entities.Medicalsupply", b =>
                {
                    b.HasOne("SchoolMedical_DataAccess.Entities.Account", "CreatedByNavigation")
                        .WithMany("Medicalsupplies")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_MedicalSupply_CreatedBy");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("SchoolMedical_DataAccess.Entities.Medicine", b =>
                {
                    b.HasOne("SchoolMedical_DataAccess.Entities.Account", "CreatedByNavigation")
                        .WithMany("Medicines")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Medicine_CreatedBy");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("SchoolMedical_DataAccess.Entities.Medicinerequest", b =>
                {
                    b.HasOne("SchoolMedical_DataAccess.Entities.Account", "ForStudentNavigation")
                        .WithMany("MedicinerequestForStudentNavigations")
                        .HasForeignKey("ForStudent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MedicineRequest_ForStudent");

                    b.HasOne("SchoolMedical_DataAccess.Entities.Account", "RequestByNavigation")
                        .WithMany("MedicinerequestRequestByNavigations")
                        .HasForeignKey("RequestBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MedicineRequest_RequestBy");

                    b.Navigation("ForStudentNavigation");

                    b.Navigation("RequestByNavigation");
                });

            modelBuilder.Entity("SchoolMedical_DataAccess.Entities.Meeting", b =>
                {
                    b.HasOne("SchoolMedical_DataAccess.Entities.Account", "HandleByNavigation")
                        .WithMany("MeetingHandleByNavigations")
                        .HasForeignKey("HandleBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Meeting_HandleBy");

                    b.HasOne("SchoolMedical_DataAccess.Entities.Account", "Student")
                        .WithMany("MeetingStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Meeting_Student");

                    b.Navigation("HandleByNavigation");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolMedical_DataAccess.Entities.Studenthealthrecord", b =>
                {
                    b.HasOne("SchoolMedical_DataAccess.Entities.Account", "CreatedByNavigation")
                        .WithMany("StudenthealthrecordCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_StudentHealthRecord_CreatedBy");

                    b.HasOne("SchoolMedical_DataAccess.Entities.Account", "Student")
                        .WithOne("StudentHealthRecord")
                        .HasForeignKey("SchoolMedical_DataAccess.Entities.Studenthealthrecord", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolMedical_DataAccess.Entities.Treatmentrecord", b =>
                {
                    b.HasOne("SchoolMedical_DataAccess.Entities.Studenthealthrecord", "StudentHealthRecord")
                        .WithMany("Treatmentrecords")
                        .HasForeignKey("StudentHealthRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TreatmentRecord_StudentHealthRecord");

                    b.Navigation("StudentHealthRecord");
                });

            modelBuilder.Entity("SchoolMedical_DataAccess.Entities.Vaccineevent", b =>
                {
                    b.HasOne("SchoolMedical_DataAccess.Entities.Account", "CreatedByNavigation")
                        .WithMany("VaccineeventCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_VaccineEvent_CreatedBy");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("SchoolMedical_DataAccess.Entities.VaccineeventStudent", b =>
                {
                    b.HasOne("SchoolMedical_DataAccess.Entities.Account", "Student")
                        .WithMany("VaccineeventStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VaccineeventStudent_Student");

                    b.HasOne("SchoolMedical_DataAccess.Entities.Vaccineevent", "Vaccineevent")
                        .WithMany("VaccineeventStudents")
                        .HasForeignKey("VaccineeventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VaccineeventStudent_Event");

                    b.Navigation("Student");

                    b.Navigation("Vaccineevent");
                });

            modelBuilder.Entity("SchoolMedical_DataAccess.Entities.Vaccinerecord", b =>
                {
                    b.HasOne("SchoolMedical_DataAccess.Entities.Studenthealthrecord", "StudentHealthRecord")
                        .WithMany("Vaccinerecords")
                        .HasForeignKey("StudentHealthRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VaccineRecord_StudentHealthRecord");

                    b.Navigation("StudentHealthRecord");
                });

            modelBuilder.Entity("SchoolMedical_DataAccess.Entities.Account", b =>
                {
                    b.Navigation("HealthcheckupeventCreatedByNavigations");

                    b.Navigation("HealthcheckupeventStudents");

                    b.Navigation("IncidentrecordHandleByNavigations");

                    b.Navigation("IncidentrecordStudents");

                    b.Navigation("InverseParent");

                    b.Navigation("Medicalsupplies");

                    b.Navigation("MedicinerequestForStudentNavigations");

                    b.Navigation("MedicinerequestRequestByNavigations");

                    b.Navigation("Medicines");

                    b.Navigation("MeetingHandleByNavigations");

                    b.Navigation("MeetingStudents");

                    b.Navigation("StudentHealthRecord");

                    b.Navigation("StudenthealthrecordCreatedByNavigations");

                    b.Navigation("VaccineeventCreatedByNavigations");

                    b.Navigation("VaccineeventStudents");
                });

            modelBuilder.Entity("SchoolMedical_DataAccess.Entities.Healthcheckupevent", b =>
                {
                    b.Navigation("HealthcheckupeventStudents");
                });

            modelBuilder.Entity("SchoolMedical_DataAccess.Entities.Studenthealthrecord", b =>
                {
                    b.Navigation("Treatmentrecords");

                    b.Navigation("Vaccinerecords");
                });

            modelBuilder.Entity("SchoolMedical_DataAccess.Entities.Vaccineevent", b =>
                {
                    b.Navigation("VaccineeventStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
